# Generated by Django 4.1.7 on 2023-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.CharField(choices=[('1', 'individual'), ('2', 'couple'), ('3', 'smallgroup'), ('4', 'largegroup'), ('5', 'preferno')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='typeofbooking',
            field=models.CharField(choices=[('1', 'Date'), ('2', 'birthday'), ('3', 'anniversary'), ('4', 'party')], default='', max_length=255),
        ),
    ]
