# Generated by Django 4.1.7 on 2023-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('entrees', 'Entrees'), ('desserts', 'Desserts')], default='', max_length=50),
        ),
    ]
