# Generated by Django 4.1.7 on 2023-03-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.TextField(default='')),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
