# Generated by Django 4.1.7 on 2023-03-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
